spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testing_db
    username: user
    password: user
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  # Opcional: para que espere a que la base de datos esté lista
  sql:
    init:
      platform: mysql
      mode: always

